# Python CircleCI 2.0 configuration file

version: 2
workflows:
  version: 2
  build-and-test:
    jobs:
      - build-2.7
      - build-3.6
jobs:
  build-3.6: &build-template 
    docker:
      - image: circleci/python:3.6-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            pip install multiprocess --user
      - run:
          name: run tests
          command: |
            sudo pip install pytest
            pytest
      - store_artifacts:
          path: test-reports
          destination: test-reports
  build-2.7:
    <<: *build-template
    docker:
        - image: circleci/python:2.7.14-stretch
